services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  db:
    image: mysql:8.3.0  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: calavera
      MYSQL_DATABASE: Confesionario
      MYSQL_USER: admin
      MYSQL_PASSWORD: calavera
    ports:
      - "3306:3306"
    volumes:
      - basedatos:/var/lib/mysql
      - ./realdatabase.sql:/docker-entrypoint-initdb.d/database.sql